name: eCommerceApplication/Release
on:
  workflow_dispatch:
env:
  buildConfiguration: Release
  buildPlatform: Any CPU
  solution: "**/*.sln"
jobs:
  Deploy_Development-Deploy:
    runs-on: ubuntu-latest
    environment:
      name: development
    if: github.RUN_NUMBER == 1
    steps:
    - name: checkout
      uses: actions/checkout@v4.1.0
    - name: download artifact
      uses: actions/download-artifact@v4.1.0
    - uses: cschleiden/webdeploy-action@v1.1.0
      with:
        webSiteName: eTickets-Dev
        package: "${{ runner.workspace }}/**/*.zip"
  Deploy_Staging-Deploy:
    needs:
    - Deploy_Development-Deploy
    runs-on: ubuntu-latest
    environment:
      name: staging
    if: success() && github.RUN_NUMBER == 1
    steps:
    - name: checkout
      uses: actions/checkout@v4.1.0
    - name: download artifact
      uses: actions/download-artifact@v4.1.0
    - uses: cschleiden/webdeploy-action@v1.1.0
      with:
        webSiteName: eTickets-Staging
        package: "${{ runner.workspace }}/**/*.zip"
  Deploy_Production-Deploy:
    needs:
    - Deploy_Staging-Deploy
    runs-on: ubuntu-latest
    environment:
      name: production
    if: success() && github.RUN_NUMBER == 1
    steps:
    - name: checkout
      uses: actions/checkout@v4.1.0
    - name: download artifact
      uses: actions/download-artifact@v4.1.0
    - uses: cschleiden/webdeploy-action@v1.1.0
      with:
        webSiteName: eTickets-Prod
        package: "${{ runner.workspace }}/**/*.zip"
